services:
  client:
    image: hvsaikrishna/budgetbuddy-frontend:latest
    ports:
      - "3200:80"
    restart: unless-stopped
    depends_on:
      - server
    pull_policy: always

  server:
    image: hvsaikrishna/budgetbuddy-backend:latest
    ports:
      - "5500:5500"
    restart: unless-stopped
    env_file:
      - .env
    pull_policy: always
